### ISSUE TITLE
Fixing your patch for kernel 4.9

### ISSUE THREAD

**Issue by neuralassembly** [doublebind/raspi#7]
On Raspberry Pi, the new kernel 4.9 returns "BCM2835" for all the versions of Pi
as "Hardware" in /proc/cpuinfo.

So, a different method is required to obtain the base adress of GPIO
(0x3f000000 for Pi2 and Pi3, and 0x20000000 for Pi1).

Based on the discussions below, I fixed your patch so that
the base address of GPIO is obtained by reading "/proc/device-tree/soc/ranges".
[https://github.com/raspberrypi/linux/issues/1902](https://github.com/raspberrypi/linux/issues/1902)

I confirmed that the new patch below works for
kernel 3.18/4.4/4.9 on Pi1/Pi2 and kernel 4.1/4.4/4.9 on Pi3. 

If you are OK, I will make a pull request.

[https://github.com/neuralassembly/raspi2/blob/master/webiopi-pi2bplus.patch](https://github.com/neuralassembly/raspi2/blob/master/webiopi-pi2bplus.patch)

**Comment by doublebind** [comment]
Thank you for adapting the patch to be compatible with the new kernel.  I appreciate the fix and the tests over multiple configurations.  Please send me your pull request.
